[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://www.agecalculater.com/*"
  to = "https://agecalculater.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.agecalculater.com/*"
  to = "https://agecalculater.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://agecalculater.com/*"
  to = "https://agecalculater.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/ads.txt"
  to = "/ads.txt"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
